func solve() {
  let target = Input.readInt()
  print(decimalToBinary(target))
  // print(containsNearbyDuplicate(arr, target))

}
func solveAndPrintValues() {
  // patternPrintingDemo()
  // print(intersection([4, 9, 5], [9, 4, 9, 8, 4]))
  // print(binarySearch([1, 2, 3, 4, 5], 3))
  // print(isSubsequence("as", "basdcas"))
  // print(majorElement([3, 2, 3, 2, 3]))
  // print(findMaxConsecutiveOnes([1, 1, 1, 1, 0, 1, 1, 1]))
  // print(majority([3, 2, 3, 4, 1, 2, 5, 3]))
  // print(findPairs([1, 3, 1, 5, 4], 1))
  // print(containsDuplicate([1, 2, 3, 4, 5]))
  // print(containsNearbyDuplicate([1, 0, 1, 1], 1))
  // removeDuplicatesDemo()
  // print(fizzBuzz(n: 15))
  // print(isPalindromicString(str: "tenet"))
  // print(firstUniqueChar(in: "interaction"))
  // print(validPalindrome("abca"))
  // print(romanToInt("MCMXCIV"))
  // print(linkedList())
  // circularLinkedListDemo()
  // print(mergeLinkedLists())
  // detectLoopInLinkedList()
  // detectCycleLoopAndLength()
  // detectStartofCycleLoopAndLength()
  // printLinkedListStack()
  // minStackDemo()
  // validParanthesisDemo()
  // validLongParanthesisDemo()
  // anagramDemo()
  // finalPricesDemo()
  // decodeXORArrayDemo()
  // sumOfUniqueDemo()
  // bubbleSortExample()
  // rotateArrayDemo()
  // print(decimalToBinary(5))
  // runCycleDetectionExamples()
  // insertionSortExample()
  // longestPalindromeDemo()
  // sortSentenceDemo()
  // defangIPaddrDemo()
  // isRotatedDemo()
  // pangramDemo()
  //  sortStringDemo()
  // sortVowelsDemo()
  //  addStringsDemo()
  // factorialDemo()
  // lengthOfLongestSubstringDemo()
  secondLargestDemo()
}
func solveSystemDesignDemo() {
  // staticAndDynamicPolymorphismDemo()
  // staticPolymorphismDemo()
  // liskovSubstitutionDemo()
  // openCloseDemo()
  // SRPDemo()
  // dependencyInversionDemo()
  // interfaceSegregationDemo()
  // documentEditorExample()
  // strategyDesignPatternDemo()
  // abstractFactoryDemo()

  // simpleSingletonDemo()

}
