func linkList() {
  let list = LinkedList<Int>()
  list.insertData(data: 10)
  list.insertData(data: 9)
  list.insertData(data: 8)
  list.insertData(data: 7)
  list.insertData(data: 6)
  list.append(5)
  print("========================")
  let found = list.find(value: 9)
  print(found?.value ?? -1)
  print("========================")
  let _ = list.delete(value: 34)
  print("========================")
  list.reverse()
  print("========================")
  list.printList()
}
